version: "3.8"

services:
  backend:
    build: ./back
    container_name: django-backend
    volumes:
      - ./back:/app
    expose:
      - "8000"
    depends_on:
      - frontend

  frontend:
    build: ./front
    container_name: vue-frontend
    volumes:
      - ./front:/app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
