# Generated by Django 4.2.11 on 2025-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=100)),
                ('link', models.URLField(unique=True)),
                ('content', models.TextField()),
                ('translated_summary', models.TextField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
