# Generated by Django 4.2.21 on 2025-05-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_salary_customuser_income_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='income',
            new_name='asset',
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
