# Generated by Django 4.2.21 on 2025-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invest_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_bank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saving_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
