# Generated by Django 4.2.11 on 2025-05-23 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_invest_type_customuser_main_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
