# Generated by Django 4.2.11 on 2025-05-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_followings'),
    ]

    operations = [
    ]
