# Generated by Django 4.2.11 on 2025-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_favoritestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='investment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
