# Generated by Django 4.2.21 on 2025-05-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=10)),
                ('save_term', models.IntegerField()),
                ('rate', models.FloatField()),
                ('fin_prdt_cd', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
