# Generated by Django 4.2.21 on 2025-05-23 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 23, 6, 42, 25, 360686, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
