# Generated by Django 4.2.11 on 2025-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
