# Generated by Django 4.2.11 on 2025-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_depositproduct_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='join_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
