# Generated by Django 4.2.11 on 2025-05-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_depositproduct_description_depositproduct_join_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositproduct',
            name='url',
        ),
    ]
