# Generated by Django 4.2.11 on 2025-05-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0006_remove_depositproduct_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='join_member',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='join_way',
            field=models.TextField(blank=True, null=True),
        ),
    ]
