# Generated by Django 4.2.11 on 2025-05-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendedstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recommendedstock',
            name='invest_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedstock',
            name='per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedstock',
            name='roe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedstock',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
