# Generated by Django 4.2.11 on 2025-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_recommendedstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedstock',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
    ]
